# Generated by Django 5.0.4 on 2024-04-25 08:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=api.models.one_week_hence)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
